# Generated by Django 5.1.15 on 2026-09-18 14:42

import django.db.models.deletion
import packaging.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "internal_length",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_strictly_positive],
                    ),
                ),
                (
                    "internal_width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_strictly_positive],
                    ),
                ),
                (
                    "internal_height",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_strictly_positive],
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_non_negative],
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_non_negative],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Boxes",
                "ordering": ["cost", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_strictly_positive],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_strictly_positive],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_strictly_positive],
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[packaging.validators.validate_non_negative],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[packaging.validators.validate_positive_quantity],
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="packaging.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="packaging.product",
                    ),
                ),
            ],
        ),
    ]
